# Generated by Django 3.0.7 on 2020-09-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_auto_20200901_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
