# Generated by Django 3.0.7 on 2020-07-31 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('term_from', models.DateTimeField(verbose_name='参画期間(自)')),
                ('term_to', models.DateTimeField(blank=True, null=True, verbose_name='参画期間(至)')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
