# Generated by Django 3.0.7 on 2020-08-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('sub_title', models.CharField(blank=True, max_length=100, verbose_name='サブタイトル')),
                ('image', models.ImageField(default='def', upload_to='portfolio/portfolio', verbose_name='アイコン画像')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日時'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, verbose_name='ポートフォリオタグ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
                ('tag', models.ForeignKey(default='ALL', on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.BooleanField(default=True, verbose_name='自己紹介')),
                ('skill', models.BooleanField(default=True, verbose_name='スキル')),
                ('portfolio', models.BooleanField(default=True, verbose_name='ポートフォリオ')),
                ('experience', models.BooleanField(default=True, verbose_name='経験')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('top_greeting', models.CharField(help_text='Topページの最初に表示される挨拶文', max_length=100, verbose_name='挨拶文')),
                ('position', models.CharField(help_text='挨拶文の下に表示される', max_length=100, verbose_name='役職・肩書き')),
                ('image', models.ImageField(default='def', upload_to='portfolio/about_me', verbose_name='アイコン画像')),
                ('text', models.TextField(max_length=400, verbose_name='説明文')),
                ('website', models.URLField(verbose_name='ウェブサイト')),
                ('twitter', models.URLField(verbose_name='Twitter URL')),
                ('github', models.URLField(verbose_name='GitHub URL')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
