# Generated by Django 3.0.7 on 2020-09-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200912_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sub_title',
            field=models.CharField(default='sub title', max_length=100, verbose_name='サブタイトル'),
            preserve_default=False,
        ),
    ]
