# Generated by Django 3.0.7 on 2020-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projecttag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='experience',
            new_name='resume',
        ),
    ]
