# Generated by Django 3.0.7 on 2020-08-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200802_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='position',
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='top_greeting',
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='main_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='メインテキスト'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='sub_text',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='サブテキスト'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(default='def.png', upload_to='portfolio/about_info', verbose_name='アイコン画像'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='resume',
            field=models.BooleanField(default=True, verbose_name='履歴'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='portfolio/portfolio/def.png', upload_to='portfolio/portfolio', verbose_name='アイコン画像'),
        ),
    ]
