# Generated by Django 3.0.7 on 2020-08-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_aboutinfo_top_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='favicon',
            field=models.ImageField(default='def_favicon.png', upload_to='portfolio/about_info', verbose_name='アイコン画像(favicon)'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='icon',
            field=models.ImageField(default='def_icon.png', upload_to='portfolio/about_info', verbose_name='アイコン画像'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='top_image',
            field=models.ImageField(default='def_top_image.png', upload_to='portfolio/about_info/top', verbose_name='Top画像'),
        ),
    ]
