# Generated by Django 3.0.7 on 2020-08-12 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0008_auto_20200812_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.IntegerField(choices=[(1, 'Front-End'), (2, 'Back-End'), (3, 'DevOps')])),
                ('skill_name', models.CharField(max_length=100, verbose_name='スキル名')),
                ('level', models.IntegerField(choices=[(1, 'Novice-初心者'), (2, 'Advanced beginnerー新人'), (3, 'Competent-一人前'), (4, 'Proficient-中堅'), (5, 'Expert-達人')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
