# Generated by Django 3.0.7 on 2020-08-13 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200813_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillClass',
            fields=[
                ('classification', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('level_text', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.SkillClass'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.SkillLevel'),
        ),
    ]
