# Generated by Django 3.0.7 on 2020-08-13 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200813_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='level',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
