# Generated by Django 3.0.7 on 2020-08-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200813_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='役割'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='役割'),
        ),
    ]
