# Generated by Django 3.0.7 on 2020-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_project_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='プロジェクト概要'),
        ),
    ]
