# Generated by Django 3.0.7 on 2020-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20200822_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='process',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='参画工程'),
        ),
    ]
