# Generated by Django 3.0.7 on 2020-09-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200901_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='text',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
