# Generated by Django 3.0.7 on 2020-09-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0018_auto_20200901_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='Demo URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='解説'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/portfolioImage', verbose_name='イメージ画像'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(choices=[(1, 'First'), (2, 'Seconf'), (3, 'Therd')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/portfolioImage', verbose_name='イメージ画像')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='作成日時')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio')),
            ],
            options={
                'unique_together': {('author', 'portfolio')},
            },
        ),
    ]
