# Generated by Django 3.0.7 on 2020-09-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200901_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='sub_title',
        ),
    ]
