# Generated by Django 3.0.7 on 2020-09-01 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0020_remove_portfolio_sub_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioimage',
            unique_together={('author', 'portfolio', 'display_order')},
        ),
    ]
