# Generated by Django 3.0.7 on 2020-09-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20200906_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutinfo',
            old_name='icon',
            new_name='avater',
        ),
    ]
